Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,4 +1,4 @@
-name: 'Terraform Plan'
+name: 'Terraform Plan/Apply'
 
 on:
   push:
@@ -21,45 +21,142 @@ permissions:
 #   ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
 
 jobs:
-  upload-files:
-    name : 'Upload Files'
-    runs-on: windows-latest
-    environment: dev
+  terraform-plan:
+    name: 'Terraform Plan'
+    runs-on: ubuntu-latest
     env:
-      TF_CLOUD_ORGANIZATION: ${{vars.TFCB_ORG}}
-      TF_WORKSPACE: ${{vars.TF_WORKSPACE}} 
+      #this is needed since we are running terraform with read-only permissions
+      ARM_SKIP_PROVIDER_REGISTRATION: true
+    outputs:
+      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
 
     steps:
     # Checkout the repository to the GitHub Actions runner
     - name: Checkout
       uses: actions/checkout@v3
-
-    - uses: hashicorp/setup-terraform@v2
+      
+    - name: Upload Configuration
+      uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
+      id: plan-upload
       with:
-        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-        terraform_wrapper: true
-      name: Terraform Install
+        workspace: ${{ env.TF_WORKSPACE }}
+        directory: ${{ env.CONFIG_DIRECTORY }}
+        speculative: true
 
-    # - name: Upload IaC
-    #   uses: actions/upload-artifact@v3
-    #   with:
-    #     name: iac
-    #     path: ${{ github.workspace }}
-
-
+    # Install the latest version of the Terraform CLI
+#     - name: Setup Terraform
+#       uses: hashicorp/setup-terraform@v2
+#       with:
+#         terraform_wrapper: false
 
     - name: Az CLI login
       uses: azure/login@v1.4.6
       with:
-        creds: ${{ secrets.AZURE_CREDS }}
+          creds: ${{ secrets.AZURE_CREDS }}
 
-    - uses: hashicorp/setup-terraform@v2
-            
-    - run: terraform init
-          
-    - id: plan
-      run: terraform plan -no-color
-          
-    - run: echo ${{ steps.plan.outputs.stdout }}
-    - run: echo ${{ steps.plan.outputs.stderr }}
-    - run: echo ${{ steps.plan.outputs.exitcode }}
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      run: terraform init
+
+    # Checks that all Terraform configuration files adhere to a canonical format
+    # Will fail the build if not
+    # - name: Terraform Format
+      # run: terraform fmt -check
+      # run: terraform fmt -autocorrect
+    # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    - name: Terraform Plan
+      id: tf-plan
+      run: |
+        export exitcode=0
+        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
+        fi
+        
+    # Save plan to artifacts  
+    - name: Publish Terraform Plan
+      uses: actions/upload-artifact@v3
+      with:
+        name: tfplan
+        path: tfplan
+        
+    # Create string output of Terraform Plan
+    - name: Create String Output
+      id: tf-plan-string
+      run: |
+        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+        
+        delimiter="$(openssl rand -hex 8)"
+        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+        echo "" >> $GITHUB_OUTPUT
+        echo '```terraform' >> $GITHUB_OUTPUT
+        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+        echo '```' >> $GITHUB_OUTPUT
+        echo "</details>" >> $GITHUB_OUTPUT
+        echo "${delimiter}" >> $GITHUB_OUTPUT
+    #  # Publish Terraform Plan as task summary
+    # - name: Publish Terraform Plan to Task Summary
+    #   env:
+    #     SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+    #   run: |
+    #     echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+      
+    # # If this is a PR post the changes
+    # - name: Push Terraform Output to PR
+    #   # if: github.ref != 'refs/heads/main'
+    #   uses: actions/github-script@v6
+    #   env:
+    #     SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
+    #   with:
+    #       github-token: ${{ secrets.GITHUB_TOKEN }}
+    #       script: |
+    #         const body = `${process.env.SUMMARY}`;
+    #         github.rest.issues.createComment({
+    #             issue_number: context.issue.number,
+    #             owner: context.repo.owner,
+    #             repo: context.repo.repo,
+    #             body: body
+    #         }) && needs.terraform-plan.outputs.tfplanExitCode == 2
+                
+  terraform-apply:
+    name: 'Terraform Apply'
+    if: github.ref == 'refs/heads/AzSample' 
+    runs-on: ubuntu-latest
+    environment: production
+    needs: [terraform-plan]
+    
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v2
+
+    - name: Az CLI login
+      uses: azure/login@v1.4.6
+      with:
+          creds: ${{ secrets.AZURE_CREDS }}
+
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      run: terraform init
+
+    # Download saved plan from artifacts  
+    - name: Download Terraform Plan
+      uses: actions/download-artifact@v3
+      with:
+        name: tfplan
+
+    # Terraform Apply
+    - name: Terraform Apply
+      run: terraform apply -auto-approve tfplan
